This time we will train with a modified reward scheme...

In [1]:
import gym
import time

In [2]:
import numpy as np

In [3]:
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
import torch
from torch import nn

In [4]:
import zeppelin_gym.env6

`polytope` failed to import `cvxopt.glpk`.
will use `scipy.optimize.linprog`


In [5]:
torch.manual_seed(42)

In [6]:
env = gym.make('zeppelin-v4')

/home/samuel/anaconda3/envs/nnv/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [7]:
env.seed(42)

In [8]:
env.unwrapped.FUEL_RESTRAINT = False
env.unwrapped.OBSTACLE_REWARD = -1.
env.unwrapped.NO_FUEL_REWARD = -0.1
# done reward = (FUEL_RESTRAINT) ? r+fuel*r : 2*r
env.unwrapped.DONE_REWARD = 0.5
env.unwrapped.INCLUDE_UNWINNABLE = False
env.unwrapped.EMERGENCY_REWARD = -1e-3
env.unwrapped.WORST_CASE_TURBULENCE=True

In [9]:
architecture = [dict(pi=[8,8], vf=[8,8])]
model = PPO("MlpPolicy", env, verbose=1,policy_kwargs={"activation_fn":nn.ReLU,"net_arch":architecture})

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [10]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

/home/samuel/anaconda3/envs/nnv/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


mean_reward:-14.20 +/- 78.44


In [11]:
def train(model,total_timesteps,num_iterations,timesteps_per_iter,eval_steps,model_name):
    print("Mean Reward \t\t Timesteps \t\t Seconds (iter)")
    for i in range(num_iterations):
        total_timesteps += timesteps_per_iter
        start_time = time.time()
        model=model.learn(total_timesteps=timesteps_per_iter,log_interval=10000)
        mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=eval_steps)
        model.save(model_name+str(total_timesteps))
        print(f"{mean_reward:.2f} +/- {std_reward:.2f}",end="\t\t")
        print(total_timesteps,end="\t\t")
        print(f"{(time.time() - start_time):.2f}s")

In [12]:
train(model,0,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

Mean Reward 		 Timesteps 		 Seconds (iter)
-4.27 +/- 21.55		100000		85.78s
-3.59 +/- 21.50		200000		81.37s
-2.85 +/- 13.07		300000		79.86s
-3.65 +/- 25.38		400000		78.35s
-2.27 +/- 5.03		500000		73.92s
-2.50 +/- 5.93		600000		72.60s
-1.93 +/- 4.56		700000		73.21s
-2.06 +/- 5.49		800000		72.58s
-1.65 +/- 3.55		900000		71.88s
-2.42 +/- 5.59		1000000		71.00s


In [13]:
train(model,1_000_000,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

Mean Reward 		 Timesteps 		 Seconds (iter)
-2.20 +/- 5.54		1100000		72.05s
-2.30 +/- 5.41		1200000		72.17s
-2.02 +/- 4.48		1300000		72.37s
-1.93 +/- 4.65		1400000		69.43s
-2.48 +/- 8.39		1500000		70.19s
-2.30 +/- 10.06		1600000		72.48s
-2.85 +/- 14.72		1700000		71.82s
-2.92 +/- 20.43		1800000		71.12s
-2.04 +/- 5.50		1900000		71.08s
-1.73 +/- 4.22		2000000		70.65s


In [14]:
train(model,2_000_000,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

Mean Reward 		 Timesteps 		 Seconds (iter)
-2.17 +/- 5.69		2100000		71.16s
-2.01 +/- 5.61		2200000		69.59s
-2.65 +/- 14.51		2300000		70.38s
-2.26 +/- 5.80		2400000		72.41s
-1.96 +/- 5.04		2500000		69.51s
-2.14 +/- 5.61		2600000		68.85s
-2.21 +/- 11.23		2700000		70.16s
-2.03 +/- 5.62		2800000		69.63s
-2.62 +/- 7.81		2900000		70.19s
-2.68 +/- 6.81		3000000		69.82s


In [15]:
train(model,3_000_000,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

Mean Reward 		 Timesteps 		 Seconds (iter)
-3.63 +/- 28.65		3100000		71.79s
-3.68 +/- 16.08		3200000		74.34s
-3.01 +/- 20.31		3300000		72.73s
-2.16 +/- 5.67		3400000		72.16s
-1.64 +/- 4.47		3500000		71.80s
-1.59 +/- 4.28		3600000		70.78s
-1.68 +/- 4.76		3700000		69.87s
-1.72 +/- 4.79		3800000		70.42s
-1.75 +/- 5.15		3900000		70.21s
-1.67 +/- 4.44		4000000		70.37s


In [16]:
train(model,4_000_000,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

Mean Reward 		 Timesteps 		 Seconds (iter)
-2.37 +/- 12.81		4100000		70.68s


KeyboardInterrupt: 

In [ ]:
train(model,5_000_000,10,100_000,1_000,"model_backup/zeppelin-v2.2-")

In [ ]:
env.seed(43)
torch.manual_seed(43)

In [10]:
model = PPO.load("model_backup/zeppelin-v2.2-1000000")
model.set_env(env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [ ]:
model = PPO.load("zeppelin-avoidance-windsystem-small2-1400000")
model.set_env(env)

In [ ]:
print("hi")
for i_episode in range(5):
    observation = env.reset()
    env.unwrapped.state=[-5,110,50,22]
    total_reward=0
    for t in range(1000):
        action, _states = model.predict(observation)
        #x1_norm = observation[0]/np.sqrt(observation[0]**2+observation[1]**2)
        #x2_norm = observation[1]/np.sqrt(observation[0]**2+observation[1]**2)
        #f = 1.0 if (x2_norm) < 0 else -1.0
        #action = [f, f*(0-x1_norm)]
        observation, reward, done, info = env.step(action)
        print(observation)
        total_reward=0.99*total_reward+reward
        env.render()
        time.sleep(0.5)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            print("Reward: ", total_reward)
            time.sleep(5.0)
            break
env.close()

In [ ]:
env.close()

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=True

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=False

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=True

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=False

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [29]:
model = PPO.load("model_backup/zeppelin-v2.2-4000000")
model.set_env(env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [30]:
torch.manual_seed(43)
env.seed(43)

In [31]:
reached_goal = 0
reached_obstacle = 0
ended_harmless = 0
for i_episode in range(10000):
    observation = env.reset()
    for t in range(1000):
        action, _states = model.predict(observation,deterministic=True)
        observation, reward, done, info = env.step(action)
        if done:
            if env.unwrapped.reached_goal(observation):
                reached_goal+=1
            elif env.unwrapped.is_crash(observation):
                reached_obstacle +=1
            else:
                ended_harmless +=1
            break
print("Goal: ", reached_goal)
print("Obstacle: ", reached_obstacle)
print("Harmless: ", ended_harmless)

Goal:  376
Obstacle:  1930
Harmless:  7694


In [24]:
env.unwrapped.INCLUDE_UNWINNABLE = False
#env.init_polytopes(0.0,retrain_polytopes_certain)
for i_episode in range(10):
    observation = env.reset()
    #env.unwrapped.state = (-200.52995,  -49.5127 ,   72.78154 ,  16.0011   , -200.83888,  -357.2502)
    observation = env.unwrapped.state
    total_reward=0
    emergencies=0
    print(observation)
    for t in range(1000):
        x1,x2,c,w,g1,g2 = observation
        #action = [0.,0.,0.0]
        
        #action=[0.,0.,1.]
        action, _states = model.predict(observation,deterministic=True)
        if action[2] > env.unwrapped.EMERGENCY_THRESHOLD:
            emergencies+=1
        #print([action[1]*action[0],action[1]*np.sqrt(1-action[0]**2)])
        observation, reward, done, info = env.step(action)
        #assert reward >= 0, f"reward: {reward}"
        #print(observation)
        #print(reward)
        total_reward=0.99*total_reward+reward
        env.render()
        time.sleep(0.01)
        if done:
            print(observation)
            print("Episode finished after {} timesteps ({} emergencies)".format(t+1,emergencies))
            print("Reward: ", total_reward)
            break
env.close()

(11.719801522828476, -18.12381758102127, 18.056895293282267, 23.814626016359313, 234.05477516465498, 143.73660312372135)
[  17.79752 -407.89762   18.0569    23.81463  234.05478  143.7366 ]
Episode finished after 23 timesteps (3 emergencies)
Reward:  -0.1024294243338249
(24.705427011254347, 39.19610885480948, 15.480028053639526, 23.475582890012316, -254.71534512017024, 30.347523750409266)
[   0.18013    6.8427    15.48003   23.47558 -254.71535   30.34752]
Episode finished after 3 timesteps (0 emergencies)
Reward:  -1.1417363631662678
(131.57939351776594, -5.479940720388441, 76.42979802076961, 23.860503281689684, 384.0554270546447, -7.88102947339604)
[ 173.63655 -407.90534   76.4298    23.8605   384.05543   -7.88103]
Episode finished after 27 timesteps (10 emergencies)
Reward:  -0.10806018371963638
(-6.0692463456440535, 42.850342928726896, 17.61353349131152, 17.97190516261096, 374.34657039035187, -364.31384759390653)
[ -45.81047 -400.90741   17.61353   17.97191  374.34657 -364.31385]
Epi

In [28]:
env.viewer.close()