This time we will train with a modified reward scheme...

In [1]:
import gym
import time

In [2]:
import numpy as np

In [3]:
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
import torch
from torch import nn

In [4]:
import zeppelin_gym.env6

`polytope` failed to import `cvxopt.glpk`.
will use `scipy.optimize.linprog`


In [5]:
torch.manual_seed(42)

In [6]:
env = gym.make('zeppelin-v4')

/home/samuel/anaconda3/envs/nnv/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [7]:
env.seed(42)

In [8]:
env.unwrapped.FUEL_RESTRAINT = False
env.unwrapped.OBSTACLE_REWARD = -1000.
env.unwrapped.NO_FUEL_REWARD = 0.1
# done reward = (FUEL_RESTRAINT) ? r+fuel*r : 2*r
env.unwrapped.DONE_REWARD = 0.5
env.unwrapped.INCLUDE_UNWINNABLE = False
env.unwrapped.EMERGENCY_REWARD = -1e-4
env.unwrapped.WORST_CASE_TURBULENCE=True

In [9]:
architecture = [dict(pi=[8,8], vf=[8,8])]
model = PPO("MlpPolicy", env, verbose=1,policy_kwargs={"activation_fn":nn.ReLU,"net_arch":architecture})

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [10]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

/home/samuel/anaconda3/envs/nnv/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


mean_reward:-713.53 +/- 1455.04


In [11]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 14.5     |
|    ep_rew_mean     | -543     |
| time/              |          |
|    fps             | 2752     |
|    iterations      | 1        |
|    time_elapsed    | 0        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 12.7        |
|    ep_rew_mean          | -577        |
| time/                   |             |
|    fps                  | 1929        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.053349447 |
|    clip_fraction        | 0.296       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.26       |
|    explained_variance   | 0.1         |
|    learning_rate        | 0.

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 13.2        |
|    ep_rew_mean          | -514        |
| time/                   |             |
|    fps                  | 1595        |
|    iterations           | 11          |
|    time_elapsed         | 14          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.021017494 |
|    clip_fraction        | 0.184       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.25       |
|    explained_variance   | 0.379       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.59e+04    |
|    n_updates            | 100         |
|    policy_gradient_loss | 0.0143      |
|    std                  | 0.997       |
|    value_loss           | 3.08e+04    |
-----------------------------------------
----------------------------------------
| rollout/                |        

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 14.5        |
|    ep_rew_mean          | -493        |
| time/                   |             |
|    fps                  | 1585        |
|    iterations           | 20          |
|    time_elapsed         | 25          |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.017391423 |
|    clip_fraction        | 0.196       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.19       |
|    explained_variance   | 0.47        |
|    learning_rate        | 0.0003      |
|    loss                 | 7.76e+03    |
|    n_updates            | 190         |
|    policy_gradient_loss | 0.00875     |
|    std                  | 0.979       |
|    value_loss           | 1.5e+04     |
-----------------------------------------
-----------------------------------------
| rollout/                |       

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 16.3        |
|    ep_rew_mean          | -421        |
| time/                   |             |
|    fps                  | 1587        |
|    iterations           | 29          |
|    time_elapsed         | 37          |
|    total_timesteps      | 59392       |
| train/                  |             |
|    approx_kl            | 0.024813723 |
|    clip_fraction        | 0.199       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.07       |
|    explained_variance   | 0.593       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.07e+03    |
|    n_updates            | 280         |
|    policy_gradient_loss | 0.00384     |
|    std                  | 0.938       |
|    value_loss           | 1.06e+04    |
-----------------------------------------
-----------------------------------------
| rollout/                |       

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 17          |
|    ep_rew_mean          | -436        |
| time/                   |             |
|    fps                  | 1594        |
|    iterations           | 38          |
|    time_elapsed         | 48          |
|    total_timesteps      | 77824       |
| train/                  |             |
|    approx_kl            | 0.026868911 |
|    clip_fraction        | 0.19        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.96       |
|    explained_variance   | 0.578       |
|    learning_rate        | 0.0003      |
|    loss                 | 3.9e+03     |
|    n_updates            | 370         |
|    policy_gradient_loss | 0.0146      |
|    std                  | 0.911       |
|    value_loss           | 1.02e+04    |
-----------------------------------------
----------------------------------------
| rollout/                |        

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 31.5       |
|    ep_rew_mean          | -375       |
| time/                   |            |
|    fps                  | 1593       |
|    iterations           | 48         |
|    time_elapsed         | 61         |
|    total_timesteps      | 98304      |
| train/                  |            |
|    approx_kl            | 0.11065402 |
|    clip_fraction        | 0.29       |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.8       |
|    explained_variance   | 0.596      |
|    learning_rate        | 0.0003     |
|    loss                 | 1.02e+03   |
|    n_updates            | 470        |
|    policy_gradient_loss | 0.029      |
|    std                  | 0.878      |
|    value_loss           | 3.7e+03    |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_me

In [12]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

mean_reward:-541.25 +/- 1019.23


In [13]:
model.save("zeppelin-v2.2-100000")

In [14]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 31.5     |
|    ep_rew_mean     | -354     |
| time/              |          |
|    fps             | 2853     |
|    iterations      | 1        |
|    time_elapsed    | 0        |
|    total_timesteps | 2048     |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 34.6       |
|    ep_rew_mean          | -421       |
| time/                   |            |
|    fps                  | 2015       |
|    iterations           | 2          |
|    time_elapsed         | 2          |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.11637619 |
|    clip_fraction        | 0.241      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.77      |
|    explained_variance   | 0.701      |
|    learning_rate        | 0.0003     |
|   

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 61.5       |
|    ep_rew_mean          | -364       |
| time/                   |            |
|    fps                  | 1595       |
|    iterations           | 11         |
|    time_elapsed         | 14         |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.06268133 |
|    clip_fraction        | 0.241      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.7       |
|    explained_variance   | 0.499      |
|    learning_rate        | 0.0003     |
|    loss                 | 6.52e+03   |
|    n_updates            | 590        |
|    policy_gradient_loss | 0.00254    |
|    std                  | 0.858      |
|    value_loss           | 8.79e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_me

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 50.5       |
|    ep_rew_mean          | -377       |
| time/                   |            |
|    fps                  | 1596       |
|    iterations           | 20         |
|    time_elapsed         | 25         |
|    total_timesteps      | 40960      |
| train/                  |            |
|    approx_kl            | 0.08163744 |
|    clip_fraction        | 0.321      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.71      |
|    explained_variance   | 0.559      |
|    learning_rate        | 0.0003     |
|    loss                 | 5.38e+03   |
|    n_updates            | 680        |
|    policy_gradient_loss | 0.0209     |
|    std                  | 0.865      |
|    value_loss           | 6.21e+03   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_me

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 31.1        |
|    ep_rew_mean          | -371        |
| time/                   |             |
|    fps                  | 1602        |
|    iterations           | 29          |
|    time_elapsed         | 37          |
|    total_timesteps      | 59392       |
| train/                  |             |
|    approx_kl            | 0.010605076 |
|    clip_fraction        | 0.144       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.7        |
|    explained_variance   | 0.543       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.43e+03    |
|    n_updates            | 770         |
|    policy_gradient_loss | -0.00293    |
|    std                  | 0.865       |
|    value_loss           | 1.06e+04    |
-----------------------------------------
-----------------------------------------
| rollout/                |       

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 33.2        |
|    ep_rew_mean          | -489        |
| time/                   |             |
|    fps                  | 1602        |
|    iterations           | 38          |
|    time_elapsed         | 48          |
|    total_timesteps      | 77824       |
| train/                  |             |
|    approx_kl            | 0.050032504 |
|    clip_fraction        | 0.209       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.77       |
|    explained_variance   | 0.574       |
|    learning_rate        | 0.0003      |
|    loss                 | 7.39e+03    |
|    n_updates            | 860         |
|    policy_gradient_loss | 0.00444     |
|    std                  | 0.883       |
|    value_loss           | 9.29e+03    |
-----------------------------------------
----------------------------------------
| rollout/                |        

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 27.4        |
|    ep_rew_mean          | -479        |
| time/                   |             |
|    fps                  | 1599        |
|    iterations           | 47          |
|    time_elapsed         | 60          |
|    total_timesteps      | 96256       |
| train/                  |             |
|    approx_kl            | 0.032806452 |
|    clip_fraction        | 0.258       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.72       |
|    explained_variance   | 0.57        |
|    learning_rate        | 0.0003      |
|    loss                 | 1.81e+03    |
|    n_updates            | 950         |
|    policy_gradient_loss | 0.0306      |
|    std                  | 0.868       |
|    value_loss           | 8.01e+03    |
-----------------------------------------
-----------------------------------------
| rollout/                |       

In [15]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

KeyboardInterrupt: 

In [ ]:
model.save("zeppelin-v2.2-200000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-300000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-400000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=500000,log_interval=10000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-1000000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=500000,log_interval=1000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-1500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=1000000,log_interval=1000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-2500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=1000000,log_interval=1000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-3500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=1000000,log_interval=1000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-4500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=1000000,log_interval=1000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-v2.2-5500000")

In [ ]:
torch.manual_seed(43)
env.seed(43)
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

Above ran while tab was closed...

In [ ]:
model = PPO.load("zeppelin-v2-5500000")
model.set_env(env)

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model = PPO.load("zeppelin-v2-400000")
model.set_env(env)

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=1000000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=1000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-6500000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1300000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1400000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1500000")

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
model = PPO.load("zeppelin-avoidance-windsystem-small2-1500000")
model.set_env(env)

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1600000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1700000")

In [ ]:
start_time = time.time()
model=model.learn(total_timesteps=100000)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model.save("zeppelin-avoidance-windsystem-small2-1800000")

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
model = PPO.load("zeppelin-avoidance-windsystem-small2-1400000")
model.set_env(env)

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, reward_threshold=1.0, n_eval_episodes=1000000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, reward_threshold=1.0, n_eval_episodes=4000000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
model = PPO.load("zeppelin-avoidance-windsystem-small2-1400000")
model.set_env(env)

In [ ]:
print("hi")
for i_episode in range(5):
    observation = env.reset()
    env.unwrapped.state=[-5,110,50,22]
    total_reward=0
    for t in range(1000):
        action, _states = model.predict(observation)
        #x1_norm = observation[0]/np.sqrt(observation[0]**2+observation[1]**2)
        #x2_norm = observation[1]/np.sqrt(observation[0]**2+observation[1]**2)
        #f = 1.0 if (x2_norm) < 0 else -1.0
        #action = [f, f*(0-x1_norm)]
        observation, reward, done, info = env.step(action)
        print(observation)
        total_reward=0.99*total_reward+reward
        env.render()
        time.sleep(0.5)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            print("Reward: ", total_reward)
            time.sleep(5.0)
            break
env.close()

In [ ]:
env.close()

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
model = PPO.load("zeppelin-avoidance-windsystem-small2-1400000")
model.set_env(env)

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=True

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=False

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
torch.manual_seed(43)
env.seed(43)

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=True

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [ ]:
env.unwrapped.WORST_CASE_TURBULENCE=False

In [ ]:
start_time = time.time()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=30000)
print("--- %s seconds ---" % (time.time() - start_time))
print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

In [10]:
model = PPO.load("zeppelin-v2.2-5500000")
model.set_env(env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [11]:
env.unwrapped.INCLUDE_UNWINNABLE = False
#env.init_polytopes(0.0,retrain_polytopes_certain)
for i_episode in range(10):
    observation = env.reset()
    observation = env.unwrapped.state
    total_reward=0
    emergencies=0
    for t in range(1000):
        #print(observation)
        x1,x2,c,w,g1,g2 = observation
        #action = [0.,0.,0.0]
        
        #action=[0.,0.,1.]
        action, _states = model.predict(observation,deterministic=True)
        if action[2] > env.unwrapped.EMERGENCY_THRESHOLD:
            emergencies+=1
        #print([action[1]*action[0],action[1]*np.sqrt(1-action[0]**2)])
        observation, reward, done, info = env.step(action)
        #assert reward >= 0, f"reward: {reward}"
        total_reward=0.99*total_reward+reward
        env.render()
        time.sleep(0.01)
        if done:
            print(observation)
            print("Episode finished after {} timesteps ({} emergencies)".format(t+1,emergencies))
            print("Reward: ", total_reward)
            break
env.close()

[ 210.01126 -402.88406   23.98714   12.03044 -238.70241  154.28203]
Episode finished after 167 timesteps (0 emergencies)
Reward:  0.09656344660313382
[-152.94023 -414.57919   35.61258   28.41249  392.57323  189.89173]
Episode finished after 35 timesteps (0 emergencies)
Reward:  -72.91031805941816
[-13.61298  24.41259  24.59131  16.11797  96.26249  86.78461]
Episode finished after 3 timesteps (0 emergencies)
Reward:  -1000.0000202798225
[ -30.10343   75.10588   78.36185   26.70478    8.14663 -104.22094]
Episode finished after 13 timesteps (0 emergencies)
Reward:  -1127.7029244266116
[  92.6957  -401.23244   15.57599   16.41171 -108.32749  347.62149]
Episode finished after 92 timesteps (0 emergencies)
Reward:  0.0980576689723
[  49.20122   31.99545   55.8393    18.97518 -133.39123 -105.46829]
Episode finished after 2 timesteps (0 emergencies)
Reward:  -1056.3491473908125
[  91.03862 -406.65768   24.31299   18.37157 -262.17891 -262.32858]
Episode finished after 47 timesteps (0 emergencies